Improved search.py
nasa/fmdtools pull request #9
Opened 2023-05-27 12:59 UTC by louwersj

made several improvements to the search.py codebase

2023-05-27 19:53 UTC, hulsed commented
See comment. Overall, search.py is not in a working state anymore/yet with this alpha version so we may have some changes in the pipeline in the next few weeks as we bring the examples up to spec.

2023-05-30 14:21 UTC, louwersj commented
@hulsed  could you still merge this imporved / cleaned one in the project main 

We could properly forked it from that point onwards.

2023-06-01 18:28 UTC, hulsed requested changes
Need to adjust some of the changes to FxnBlock

2023-06-01 18:28 UTC, hulsed commented on fmdtools/sim/search.py
> +            # Create a new model and scenario for sequence simulation
I worry about removing mdl_s here. I think it's supposed to get fed into prop.prop_one_scen on line 328.

2023-06-01 18:28 UTC, hulsed commented on fmdtools/define/block.py
> +    def __init__(self, name='', flows={}, args_f=dict(), **kwargs):
This is removing too many attributes and will break certain models/workflows that rely on the ASG and CompArch types:
- c and a are instantiated just a bit below, so they need to be kept here
- local needs to be kept (and I think is supposed to call add_local_to_flowdict, which I think is supposed to happen in comms also--so, would make a good issue/bug report)
- The previous docs for parameters is mostly accurate--p,s,r,m,t, and sp are all parameters that get passed as kwargs to Block. Maybe we need a better way of documenting?

2023-06-02 14:00 UTC, louwersj commented on fmdtools/define/block.py
> +    def __init__(self, name='', flows={}, args_f=dict(), **kwargs):
Moving this back into the code

2023-06-02 14:02 UTC, louwersj commented on fmdtools/sim/search.py
> +            # Create a new model and scenario for sequence simulation
Should be resolved in the latest code drop.

2023-06-02 17:33 UTC, hulsed commented on fmdtools/define/block.py
> +    def __init__(self, name='', flows={}, args_f=dict(), **kwargs):
It looks like your latest commit only has the changes to search.py--make sure this makes it in and I'll merge the PR

2023-06-02 17:34 UTC, hulsed commented
> @hulsed changes are made to correct the requested. Can you have a quick check on the two changes done to search.py and block.py ?

I don't see that the corrections to block.py made it in but will once they are there

2023-06-05 08:45 UTC, louwersj commented
adding corrections to block.py @hulsed

2023-06-05 23:28 UTC, hulsed approved these changes

2023-06-05 23:28 UTC, merged